# Generated by Django 5.0.4 on 2024-04-08 09:19

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_roomphotos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
