# Generated by Django 5.0.4 on 2024-04-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_host_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomphotos',
            name='caption',
            field=models.CharField(blank=True, default='This is a Image of the room', max_length=255, null=True),
        ),
    ]
