# Generated by Django 5.0.4 on 2024-04-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_status_bookedday_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='revied',
            field=models.BooleanField(default=False),
        ),
    ]
