# Generated by Django 5.0.4 on 2024-04-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_revied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='revied',
            new_name='reviewed',
        ),
    ]
