# Generated by Django 5.0.4 on 2024-04-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_rename_revied_reservation_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_of_guests',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
