# Generated by Django 5.0.1 on 2024-02-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_initial'),
        ('rooms', '0004_alter_roomphotos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='rooms.room'),
        ),
    ]
